### PR TITLE
chore: fix pipeline

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by recena** [comment]
Thanks a lot @jstrachan https://twitter.com/recena/status/1089119428531359744

**Comment by recena** [comment]
I think we should update the POM file in the`master`branch https://github.com/jenkinsci/jx-resources-plugin/blob/master/pom.xml#L12

**Comment by jstrachan** [comment]
@recena the only modification done during the build process is to change the `<version>` tag which we make on the release branch/tag - there's no real need to update the master branch snapshot version every time you release - its clear from the releases page + tags a release has taken place.

The main reason we don't update the master branch is we default to releasing on a merge to master - so we'd have an infinite release loop if we had to commit to the master branch on each release as well

**Comment by recena** [comment]
@jstrachan How do you set the version number during the release process? Now, you are building thinks like that `1.0.X` (basically, an auto incremental revision). What does it happens whether we want something like `1.1.x` or `2.0.X`?

IMHO, we are not following the common conventions in Maven projects where it uses semantic versioning.

**Comment by jglick** [comment]
@jstrachan was there some process creating releases out of `master` commits in this repo? Because if so, it seems to have ended after `1.0.33`, just after this was merged. [Subsequent merged changes](https://github.com/jenkinsci/jx-resources-plugin/compare/v1.0.33...master) are unreleased.

**Comment by jglick** [comment]
Well we got a [couple releases](https://github.com/jenkinsci/jx-resources-plugin/compare/v1.0.33...v1.0.35) from @jenkins-x-bot but now it seems to be [broken again](https://github.com/jenkinsci/jx-resources-plugin/compare/v1.0.35...master) so #29 is not available. Should I be cutting releases manually, as is done for almost every other Jenkins plugin, or is there still supposed to be some JX automation in here somewhere @jstrachan @rawlingsj?

**Pull request merged**
